# Google App Engine configuration for Bakery Inventory Management System
# Alternative to Cloud Run deployment
# Deploy with: gcloud app deploy

runtime: python311
entrypoint: gunicorn -b :$PORT --workers 2 --threads 4 --timeout 0 app:app

# Environment variables (use Secret Manager for sensitive values)
env_variables:
  FLASK_ENV: "production"
  # Note: Do not put sensitive values here!
  # Use Secret Manager instead (see beta_settings below)

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

# Instance class
instance_class: F2

# Handlers for static files (optional - improves performance)
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Cloud SQL configuration
# Replace YOUR_PROJECT_ID and REGION with your actual values
beta_settings:
  cloud_sql_instances: "YOUR_PROJECT_ID:REGION:bakery-db"

# Health checks
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
