# Google App Engine configuration
runtime: python311
entrypoint: gunicorn -b :$PORT --workers 2 --threads 4 app:app

# Environment variables
env_variables:
  SECRET_KEY: "change-this-in-production"
  FLASK_ENV: "production"

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

# Instance class
instance_class: F2

# Handlers for static files (optional - improves performance)
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
